# Use the official .NET image, based on Debian.
# See https://hub.docker.com/_/microsoft-dotnet-sdk/ for more info.
image: mcr.microsoft.com/dotnet/sdk:8.0

build:
  stage: build
  script: 
    # Restore any NuGet packages.
    - dotnet restore ./Mocktrix/Mocktrix.sln
    # Build projects.
    - dotnet build ./Mocktrix/Mocktrix.sln
    # Run tests for Mocktrix.Data.
    - cd Mocktrix.Data.Tests
    - dotnet test
    # Run tests for Mocktrix server.
    - cd ../Mocktrix/
    - dotnet run &
    - sleep 5
    - cd ../MocktrixTests/
    - dotnet test
