name: .NET

on: push

jobs:
  dotnet:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git tar bzip2
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore projects
        run: |
          dotnet restore ./Mocktrix/Mocktrix.sln
      - name: Build projects
        run: |
          dotnet build ./Mocktrix/Mocktrix.sln
      - name: Run tests for Mocktrix.Configuration
        run: |
          cd "$GITHUB_WORKSPACE"/Mocktrix.Configuration.Tests/
          dotnet test
      - name: Run tests for Mocktrix.Data
        run: |
          cd "$GITHUB_WORKSPACE"/Mocktrix.Data.Tests/
          dotnet test
      - name: Run tests for Mocktrix.Database.Memory
        run: |
          cd "$GITHUB_WORKSPACE"/Mocktrix.Database.Memory.Tests/
          dotnet test
      - name: Run tests for Mocktrix server
        run: |
          cd "$GITHUB_WORKSPACE"/Mocktrix/
          dotnet run &
          while ! netstat -tna | grep LISTEN | grep --silent 5289
          do
              echo Waiting for Kestrel server to start ...
              sleep 5
          done
          cd ../Mocktrix.Tests/
          dotnet test
      - name: Publish application
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir -p artifacts/publish
          RIDS="linux-arm linux-arm64 linux-x64 linux-musl-x64 osx-x64 osx-arm64 win-x64 win-x86"
          for RID in $RIDS
          do
            DEST_NAME=Mocktrix-$RID
            DESTINATION=$GITHUB_WORKSPACE/artifacts/publish/${DEST_NAME}
            dotnet publish ./Mocktrix/Mocktrix.csproj -c Release -r $RID -o $DESTINATION
            rm "$DESTINATION"/*.pdb
            cp LICENSE $DESTINATION/
            cp readme.md $DESTINATION/
            cp third-party.md $DESTINATION/
            cd "$GITHUB_WORKSPACE/artifacts/publish"
            tar cjf ${DEST_NAME}.tar.bz2 $DEST_NAME
            cd "$GITHUB_WORKSPACE"
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mocktrix-Artifacts
          if-no-files-found: error
          path: artifacts/publish/Mocktrix*.tar.bz2
